---
acc_cluster:
  - Name: SysVal
  # Need to add Path
  - DMA:
    - Name: ClusterDMA
      Size: 128
      MaxReq: 4
      Type: NonCoherent
      InterruptNum: 123
  - DMA:
    - Name: StreamDMA0
      PIO: 32
      Size: 8
      Type: Stream
      ReadInt: 124
      WriteInt: 125
  - Accelerator:
    - Name: top
    # Need to add config and IR configurations here
      PIO: 32
      Bus: Local
      # Interrupt: 97 Need to Implement?
  - Accelerator:
    - Name: bench
      PIO: 32
      PIOMaster: top
      ResetSPM: True
      # Interrupt: 98 Need to implement?
    - Var:
      - Name: Matrix0
        Type: SPM
        Size: 2048
        Ports: 2
    - Var:
      - Name: Matrix1
        Type: SPM
        Size: 2048
        Ports: 2
    - Var:
      - Name: Matrix2
        Type: SPM
        Size: 2048
        Ports: 2
    - Var:
      - Name: Matrix3
        Type: Stream
        StreamSize: 1
        BufferSize: 8
        InCon: top
        OutCon: bench
---
acc_cluster:
  - Name: SecondGEMM
  - Accelerator:
    - Name: GEMM2
      PIO: 32
      Bus: Local
    - Var:
      - Name: Matrix0
        Type: SPM
        Size: 2048
        Ports: 2

  # - Accelerator:
  #   - Name: GEMM2
  #   - Vars:
  #     - Matrix0:
  #       - Size: 2048
  #       - Type: SPM
  #     - Matrix1:
  #       - Size: 2048
  #       - Type: SPM
  #     - Matrix2:
  #       - Size: 2048
  #       - Type: SPM
  # For Comminterface Local, ACP, Stream, SPM, PIO
  # All can have multiple connections